#server:
#  port: 8848
#  servlet:
#    context-path: /yml
#
student:
  name: "易烊千玺"                    # 字符串
  age: 21                             # 数值
  gender: "男"                        # 布尔值
  birthday: 2000/1/1 12:30:20         # 日期
  hobby: ["唱", "跳", "rap"]          # 数组
  food:                               # 集合
    - 烤羊排
    - 烤韭菜
    - 烤鱿鱼
  score: {"Java": 100, "MySQL": 100}  # Map
  car:                                # 对象
    name: 比亚迪
