# 配置数据源
spring:
  main:
    # 允许循环依赖
    allow-circular-references: true
  datasource:
    # 使用默认的Hikari数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bills?useSSL=false&useUnicode=true&characterEncoding=UTF8&serverTimeZone=GTM+8
    username: root
    password: 200202
  #thymeleaf的配置
  thymeleaf:
    cache: false
    enabled: true
#      web-stat-filter:
#        enabled: true
#        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"
#配置mybatisplus
#mybatis-plus:
#  mapper-locations:
#    - classpath:mapper/*Mapper.xml
#  global-config:
#    db-config:
#      id-type: auto
#    banner: true
# MyBatis配置
mybatis:
  # mybatis配置文件的路径
  # config-location:
  mapper-locations: com/lz/mapper/*.xml
  type-aliases-package: com.lz.entity
  configuration:
    # 二级缓存
    cache-enabled: true
    # 日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # 主键回填
    use-generated-keys: true
    # 懒加载
    lazy-loading-enabled: true
    # 积极加载
    aggressive-lazy-loading: false
    # 驼峰命名
    map-underscore-to-camel-case: true